### ISSUE TITLE
Error locating target 'teach.data.BABELDataModule',

### ISSUE THREAD

**Issue by Lyris01** [atnikos/sinc#3]
Error occurs when sampling:
Error locating target 'teach.data.BABELDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: data
AttributeError: module 'teach.data' has no attribute 'BABELDataModule'

During handling of the above exception, another exception occurred:

ModuleNotFoundError: No module named 'teach.data.BABELDataModule'

where should I put the teach folder and how to fix this issue?

**Comment by athn-nik** [comment]
The code is not yet ready for sampling and evaluation. The instructions about teach refer only to data processing, so you can train the model. I will release a strict for synthetic data creation and the checkpoints in the future. For now, the code is available for training your own models and checking the synthetic data creation pipeline.
